### ISSUE TITLE
k8s-gke-service-account-assigner does not work with GKE Metadata concealment

### ISSUE THREAD

**Issue by stepanstipl** [imduffy15/k8s-gke-service-account-assigner#7]
k8s-gke-service-account-assigner does not work when [GKE Metadata concealment](https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#concealment) is enabled on the cluster.

This is caused by iptables rule redirecting all the traffic to GKE's [k8s-metadata-proxy](https://github.com/GoogleCloudPlatform/k8s-metadata-proxy) that is already present and therefore takes precedence before the rule appended by k8s-gke-service-account-assigner.

**Comment by imduffy15** [comment]
@stepanstipl Are you happy for this to be marked as resolved with your PR merged?

**Comment by imduffy15** [comment]
Travis just finished publishing the 0.0.2 image for this: https://cloud.docker.com/repository/docker/imduffy15/k8s-gke-service-account-assigner/tags

**Comment by stepanstipl** [comment]
Awesome, thanks a lot for merging this! 👍
